// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTyDCF5p1TxjEQ40-Wo2nXo6IRRe_sy44',
    appId: '1:970326676300:web:70971d06f9dd947a69f5e9',
    messagingSenderId: '970326676300',
    projectId: 'routine-log-app',
    authDomain: 'routine-log-app.firebaseapp.com',
    storageBucket: 'routine-log-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrjJyuCSZ6-fdxl5jBGCUKA_mn_0-sMCg',
    appId: '1:970326676300:android:e5ce74c8ed06fd3c69f5e9',
    messagingSenderId: '970326676300',
    projectId: 'routine-log-app',
    storageBucket: 'routine-log-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZLXWr6YGnLQhHoYEvEfMr3xUhU7fO7vo',
    appId: '1:970326676300:ios:8da5f927c58c13fe69f5e9',
    messagingSenderId: '970326676300',
    projectId: 'routine-log-app',
    storageBucket: 'routine-log-app.firebasestorage.app',
    iosBundleId: 'com.routinelog.routinelogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZLXWr6YGnLQhHoYEvEfMr3xUhU7fO7vo',
    appId: '1:970326676300:ios:8da5f927c58c13fe69f5e9',
    messagingSenderId: '970326676300',
    projectId: 'routine-log-app',
    storageBucket: 'routine-log-app.firebasestorage.app',
    iosBundleId: 'com.routinelog.routinelogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTyDCF5p1TxjEQ40-Wo2nXo6IRRe_sy44',
    appId: '1:970326676300:web:c4e895a04f6305ec69f5e9',
    messagingSenderId: '970326676300',
    projectId: 'routine-log-app',
    authDomain: 'routine-log-app.firebaseapp.com',
    storageBucket: 'routine-log-app.firebasestorage.app',
  );
}
